server:
  port: 8800
  
eureka:
  client:
    service-url:
      defaultZong: http://localhost:8761/cloud-eureka/ #eureka服务注册中心地址
  instance:
    prefer-ip-address: true #采用IP注册
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    

spring:
  application:
    name: cloud-user
    #非
 # could的配置信息一定要写到bootstrap.yml中
  # 因为cloud框架会优先读取bootstrap.yml配置文件，如果发现这里面没有这些配置，那么是无法将当前服务注册到注册中心的，这点需要特别注意，服务名也要写到ootstrap.yml文件中哦
  cloud:
    config:
      discovery:
        enabled: true   #如果希通过在配置中心找服务名的方式招待配置中心，那么这个属性就要设置成 true  默认false
        service-id: cloud-config #配置中心的服务名
      fail-fast: true   #将这个设置成true 表示连接配置中心失败，让程序启动失败
  

